from mongoengine import Document, StringField, FloatField, IntField


class Weather(Document):
    stationID = StringField()
    tz = StringField()
    obsTimeUtc = StringField()
    obsTimeLocal = StringField()
    epoch = IntField()
    lat = FloatField()
    lon = FloatField()
    solarRadiationHigh = StringField()
    uvHigh = StringField()
    winddirAvg = FloatField()
    humidityHigh = FloatField()
    humidityLow = FloatField()
    humidityAvg = FloatField()
    qcStatus = FloatField()
    tempHigh = FloatField()
    tempLow = FloatField()
    tempAvg = FloatField()
    windspeedHigh = FloatField()
    windspeedLow = FloatField()
    windspeedAvg = FloatField()
    windgustHigh = FloatField()
    windgustLow = FloatField()
    windgustAvg = FloatField()
    dewptHigh = FloatField()
    dewptLow = FloatField()
    dewptAvg = FloatField()
    windchillHigh = FloatField()
    windchillLow = FloatField()
    windchillAvg = FloatField()
    heatindexHigh = FloatField()
    heatindexLow = FloatField()
    heatindexAvg = FloatField()
    pressureMax = FloatField()
    pressureMin = FloatField()
    pressureTrend = FloatField()
    precipRate = FloatField()
    precipTotal = FloatField()
